# packages for minemeld
structure_packages:
  - p7zip
  - p7zip-plugins
  - bzip2
  - git
  - gcc-c++
  - leveldb-devel
  - rrdtool-devel
  - libxslt-devel
  - c-ares-devel
  - snappy-devel
  - python-devel
  - Cython

distribution_post_task: CentOS-7-post

#python_executable: /usr/local/bin/python2.7
