www_directory: "{{main_directory}}/www"
www_venv_directory: "{{www_directory}}/venv"
webui_repo_directory: "{{www_directory}}/webui"
venv_directory: "{{main_directory}}/engine/current"
prototypes_local_directory: "{{local_directory}}/prototypes"
prototypes_repo_directory: "{{main_directory}}/prototypes"
local_directory: "{{main_directory}}/local"
data_directory: "{{local_directory}}/data"
config_directory: "{{local_directory}}/config"
api_config_directory: "{{config_directory}}/api"
traced_config_directory: "{{config_directory}}/traced"
trace_directory: "{{local_directory}}/trace"
library_directory: "{{local_directory}}/library"
certs_directory: "{{local_directory}}/certs"
local_ca_directory: "{{local_directory}}/certs/site"
supervisor_directory: "{{main_directory}}/supervisor"
engine_directory: "{{main_directory}}/engine"
