- name: minemeld-node-prototypes repo
  git:
    repo: "{{prototype_repo}}"
    clone: yes
    dest: "{{prototypes_repo_directory}}/minemeld-node-prototypes"
    version: "{{minemeld_version}}"
- name: minemeld-node-prototypes current link
  file:
    src: "{{prototypes_repo_directory}}/minemeld-node-prototypes/prototypes"
    dest: "{{prototypes_repo_directory}}/current"
    state: link
    owner: minemeld
    group: minemeld
